### PR TITLE
Android: Handle share intents when app first launches

### LINKED ISSUE #8513: Android share extension not working if app not open in background
### Steps to Reproduce

1. Make sure the app isn't running in the background on android
2. Share some content from another app, select Bluesky in the share menu
3. Notice that I am on the timeline, not composing a post.

It works correctly if the app was left running in the background on android

### Attachments

_No response_

### What platform(s) does this occur on?

Android

### Device Info

_No response_

### What version of the app are you using?

Build version: 1.103.0.653; Bundle info: 3ee093ea6 (prod); Bundle date: 25061318; Platform: android; Platform version: 35; Anonymous ID: 56cc1e5a-8926-4a9a-9d8f-069e995b2572

### Additional Information

Originally reported in https://github.com/bluesky-social/social-app/issues/4799#issuecomment-2271029690, but I'm creating a new issue because that one is seemingly different.

Looking through the code, the issue seems to be that `onNewIntent` doesn't run if the activity has to start https://github.com/bluesky-social/social-app/blob/9cf457acf8495c1287e366f677e1516847e4d739/modules/expo-receive-android-intents/android/src/main/java/xyz/blueskyweb/app/exporeceiveandroidintents/ExpoReceiveAndroidIntentsModule.kt#L26-L28 I found this StackOverflow answer that may be helpful: https://stackoverflow.com/a/36942185

### PR DESCRIPTION
**Pull request by mozzius**
Fixes #8513

The share intent handler only handles new incoming intents - if the app was initialised with an intent, it doesn't get picked up. Fix is to read the current intent in `OnCreate` and handle that

This is similar to #8513 but that one also adds a timeout - in my testing the timeout is not necessary. I checked it on a mid-range and low-end real device and it works fine.

# Test plan

Create a production build on a real device. Make sure the app is fully dead. Share something (i.e. a link) to Bluesky and confirm it works.

- [x] I have tested thoroughly myself

### CODE REVIEW

File: src/lib/hooks/useIntentHandler.ts [hunk 1]
```diff
@@ -24,7 +24,7 @@ const VALID_IMAGE_REGEX = /^[\w.:\-_/]+\|\d+(\.\d+)?\|\d+(\.\d+)?$/
 let previousIntentUrl = ''
 
 export function useIntentHandler() {
-  const incomingUrl = Linking.useURL()
+  const incomingUrl = Linking.useLinkingURL()
```
Comment (mozzius) [inline src/lib/hooks/useIntentHandler.ts:27]: `useURL` is deprecated in favour of `useLinkingURL`. I found that they act similarly, except `useLinkingURL` initialises with the correct value whereas `useURL` always initialises with `null`. Seems better.
