### PR TITLE
resolve did before loading feed

### LINKED ISSUE #1088: "See more from" in My Feeds going to wrong link
**Describe the bug**

The **See more from [. . .] feed** goes to an erroneous link to a feed that doesn't exists, because it's using the user handle of the the feed creator rather than the did.

**To Reproduce**

1. Go to My Feeds.
2. Scroll down a feed to get to the "**See more from**" link.
3. Click it and go to the page it takes you to.

**Expected behavior**

The URLs for feeds have always used did instead of user name, from what I've always noticed. If I replace the user name with the proper did, I'm shown the feed that I am expecting. 

**Screenshots**

wrong

right

**Details**

 - Platform: Windows Desktop

**Additional context**

This seems like a very recent change? Maybe user handle is intended to be a valid link in a coming update but that seems not like a great idea?

### PR DESCRIPTION
**Pull request by estrattonbailey**
Fixes #1088

The `Feed` component has a nice skeleton loading state, but handling DID resolution in the main body of the inner component results in a lot of conditionals and updates to allow undefined values (see `PostsFeedModel` and `useCustomFeed` params for example).

Handling it before this component even renders is a simpler data flow, but with the drawback of a small loading state prior to the main feed loading state.

Both loading and error state were lifted from the main post screen.

https://github.com/bluesky-social/social-app/assets/4732330/e0343a39-0bf8-4b1a-8237-7568681e876d

Screen Shot 2023-08-03 at 11 35 45 AM
Screen Shot 2023-08-03 at 11 35 53 AM

### CODE REVIEW

File: src/view/screens/CustomFeed.tsx [hunk 1]
```diff
@@ -34,17 +34,41 @@ import {EmptyState} from 'view/com/util/EmptyState'
...
+
+    fetchDid()
+  }, [store, handleOrDid, setFeedOwnerDid])
+
+  return feedOwnerDid ? (
+    <CustomFeedScreenInner {...props} feedOwnerDid={feedOwnerDid} />
+  ) : null
+})
+
+export const CustomFeedScreenInner = withAuthRequired(
```
Comment (pfrazee) [inline src/view/screens/CustomFeed.tsx:63]: Is there any reason not to wrap the outer element with `withAuthRequired`? Right now the `resolveName` call will fail without auth so using it outside of the auth wrapper has the potential to trigger weird states

File: src/view/screens/CustomFeed.tsx [hunk 2]
```diff
@@ -34,17 +34,41 @@ import {EmptyState} from 'view/com/util/EmptyState'
...
+  const store = useStores()
+  const {name: handleOrDid} = props.route.params
+  const [feedOwnerDid, setFeedOwnerDid] = React.useState<string | undefined>()
+
+  React.useEffect(() => {
+    /*
+     * We must resolve the DID of the feed owner before we can fetch the feed.
+     */
+    async function fetchDid() {
+      const did = await resolveName(store, handleOrDid)
```
Comment (pfrazee) [inline src/view/screens/CustomFeed.tsx:51]: Do we need error handling here?

File: src/view/screens/CustomFeed.tsx [hunk 3]
```diff
@@ -34,17 +34,41 @@ import {EmptyState} from 'view/com/util/EmptyState'
...
+      setFeedOwnerDid(did)
+    }
+
+    fetchDid()
+  }, [store, handleOrDid, setFeedOwnerDid])
+
+  return feedOwnerDid ? (
+    <CustomFeedScreenInner {...props} feedOwnerDid={feedOwnerDid} />
+  ) : null
```
Comment (pfrazee) [inline src/view/screens/CustomFeed.tsx:60]: Probably should put a loading spinner or something here, it's entirely possible the network call could hang and this would leave it on a blank screen

**Review by pfrazee — CHANGES_REQUESTED** [review]
Yeah this makes sense to me -- moving it into the model is a bigger pain than it's worth.

A couple of requested changes and questions but otherwise 👍

File: src/view/screens/CustomFeed.tsx (hunk 1 above)
Comment (estrattonbailey) [reply src/view/screens/CustomFeed.tsx]: Overlooked this, good call!

File: src/view/screens/CustomFeed.tsx (hunk 2 above)
Comment (estrattonbailey) [reply src/view/screens/CustomFeed.tsx]: We do indeed 👍

**Comment by estrattonbailey** [comment]
@pfrazee lmk thoughts on error message. We only get a `400` and `Unable to resolve handle` from the backend rn.

**Review by pfrazee — APPROVED** [review]
