### PR TITLE
#1001 Modal content overflow

### LINKED ISSUE #1001: [Web] A lot of post content in a modal causes parts of modal to become inaccessible
**Describe the bug**
Adding enough post content like media and long text content in the "Create Post" modal causes the modal header actions like "Cancel" or "Post" to be hidden

**To Reproduce**

1. Open your [Bluesky timeline](https://bsky.app/)
2. Click "New Post" primary action button
3. Add media _(you can use the reproduction screenshot)_ and text content _(you can use the reproduction steps text)_
4. See the modal header actions are hidden behind the browser app bar

**Expected behavior**

The modal UI
- **either** shrinks
- **or** becomes scrollable

**Screenshots**

bsky-modal-overflow-scrsht

**Details**

 - Platform: Desktop Firefox MacOS
 - Platform version: MacOS Sonoma 14.0 Beta 3, Firefox Developer Edition 116.0b2 (64-bit)
 - App version: 1.41.0

**Additional context**

Potentially related to #1000

### PR DESCRIPTION
**Pull request by estrattonbailey**
Fixes #1001 

Seemed to me like based on original the styles that the mobile version here was supposed to fill the screen, so that's what I did. I tried an option with a gutter all the way around the `Composer`, but decided on small devices that it was too scrunched atm.

On desktop, I chose an arbitrary gutter of 40px, lmk if we've got more specific values for this.

Screenshots ordered by increasing screen size:
Screen Shot 2023-07-18 at 15 13 04
Screen Shot 2023-07-18 at 15 13 28
Screen Shot 2023-07-18 at 15 13 49
Screen Shot 2023-07-18 at 15 23 04
Screen Shot 2023-07-18 at 15 14 03

### CODE REVIEW

File: src/view/shell/bottom-bar/BottomBarStyles.tsx [hunk 1]
```diff
@@ -1,8 +1,11 @@
 import {StyleSheet} from 'react-native'
 import {colors} from 'lib/styles'
 
+export const BOTTOM_BAR_HEIGHT = 61
+
 export const styles = StyleSheet.create({
   bottomBar: {
+    height: BOTTOM_BAR_HEIGHT,
```
Comment (estrattonbailey) [inline src/view/shell/bottom-bar/BottomBarStyles.tsx:8]: This was its natural height in my browser, and since I wanted to use it as whitespace around the `Composer`, ideally we make it an explicit relationship so that updates here are reflected in the `Composer`.

File: src/view/shell/Composer.web.tsx [hunk 2]
```diff
@@ -62,7 +63,8 @@ const styles = StyleSheet.create({
     paddingVertical: 0,
     paddingHorizontal: 2,
     borderRadius: isMobileWeb ? 0 : 8,
-    marginBottom: '10vh',
+    marginBottom: isMobileWeb ? BOTTOM_BAR_HEIGHT : 0,
     borderWidth: 1,
+    maxHeight: isMobileWeb ? `calc(100% - ${BOTTOM_BAR_HEIGHT}px)` : 'calc(100% - (40px * 2))',
```
Comment (estrattonbailey) [inline src/view/shell/Composer.web.tsx:68]: `40px * 2` e.g. a gutter on each side

**Review by pfrazee — APPROVED** [review]
Looks great!
