### PR TITLE
Use ALF for the birthday modal and remove legacy one

### LINKED ISSUE #3210: Save button in My Birthday sheet is cut off on smaller screen sizes in initial view
**Describe the bug**

On devices with smaller screens, the Save button is initially cut off in the bottom sheet that appears if you tap to show your birthday in Settings.

**To Reproduce**

1. Open Settings
2. Tap Show next to Birthday:
3. Observe that the Save button is cut off if you're using a smaller screen device. The sheet can be dragged up to show it, but this may not be obvious to some users.

**Expected behavior**

The bottom sheet opens so that the Save button is fully displayed without having to drag up the bottom sheet.

**Screenshots**

IMG_5770

**Details**

 - Platform: iOS / iPadOS
 - Platform version: 16.6.1
 - App version: 1.72

### PR DESCRIPTION
**Pull request by mozzius**
image

Fixes #3210

ALF'd the birthday modal into a Dialog

Screenshot 2024-03-15 at 15 42 14

Screenshot 2024-03-15 at 15 42 19

Screenshot 2024-03-15 at 16 04 18

### CODE REVIEW

File: src/components/dialogs/BirthDateSettings.tsx [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+    <View style={a.gap_lg}>
+      <View style={[a.gap_sm]}>
+        <Text style={[a.text_2xl, a.font_bold]}>
+          <Trans>My Birthday</Trans>
+        </Text>
+        <Text style={t.atoms.text_contrast_medium}>
+          <Trans>This information is not shared with other users.</Trans>
+        </Text>
+      </View>
+      <DateInput
```
Comment (haileyok) [inline src/components/dialogs/BirthDateSettings.tsx:92]: If you wrap this in an `a.align_center` it should center it within the dialog on iOS instead of pushing it over to the left.

Comment (mozzius) [reply src/components/dialogs/BirthDateSettings.tsx:92]: Good shout, was on a small iOS so didn't see that behaviour

Comment (mozzius) [reply src/components/dialogs/BirthDateSettings.tsx]: lol it's really obvious in the screenshot now you've pointed it out, how did I not notice

**Comment by haileyok** [comment]
Oop I think adding the center removed the full width from the picker on web 😆 
Screenshot 2024-03-15 at 9 14 07 AM

One other thing, can we see if this works inside a `ScrollableInner`? This could be a problem

Screenshot 2024-03-15 at 9 10 26 AM

**Comment by mozzius** [comment]
Done and done. ScrollableInner seems to work just fine

**Comment by haileyok** [comment]
🤌

**Review by haileyok — APPROVED** [review]
