### PR TITLE
fix: click on our profile when seeing someone's profile

### LINKED ISSUE #7699: Can't click on your own profile when seeing someone's profile
### Steps to Reproduce

1. Open someone's profile on Chrome
2. Click on your own profile at the right bottom
3. It does nothing

### Attachments

Image

### What platform(s) does this occur on?

Web (Mobile)

### Device Info

Android 10

### What version of the app are you using?

Chrome 132.0 (but also in older ones)

### Additional Information

It's a rather new bug but I don't remember how new. Maybe under 3 months?

### PR DESCRIPTION
**Pull request by NicolasBorlet**
Resolves  #7699

### CODE REVIEW

File: src/view/shell/bottom-bar/BottomBarWeb.tsx [hunk 1]
```diff
@@ -240,18 +240,28 @@ const NavItem: React.FC<{
     }
     return getCurrentRoute(state)
   })
+
+  // Détermine si nous sommes sur le profil de quelqu'un d'autre
```
Comment (Signez) [inline src/view/shell/bottom-bar/BottomBarWeb.tsx:244]: Just a head's up: comments in Bluesky's code are in French.

```suggestion
  // Checks whether we're on someone else's profile
```

Comment (NicolasBorlet) [reply src/view/shell/bottom-bar/BottomBarWeb.tsx]: mb thanks !

**Review by Signez — COMMENTED** [review]
Seems fine to me, but I am not part of the Bluesky core team — I am only a drive-by contributor and regular translator — so a review from me is not really useful.

Pinging @mozzius, maybe? But please keep in mind that Bluesky's team members are always busy and may not take a look to your contributions if they are both unsolicited (did not fix an issue they acknowledged) and unexpected (you didn't talk with them about it).

**Comment by NicolasBorlet** [comment]
> Seems fine to me, but I am not part of the Bluesky core team — I am only a drive-by contributor and regular translator — so a review from me is not really useful.
> 
> Pinging @mozzius, maybe? But please keep in mind that Bluesky's team members are always busy and may not take a look to your contributions if they are both unsolicited (did not fix an issue they acknowledged) and unexpected (you didn't talk with them about it).

Thanks for your response, I thought you were one of them.. 

Yes of course, it's the first time I'm participating so I didn't know if I should tag the issue (https://github.com/bluesky-social/social-app/issues/7699) I'm solving and if I should put screen records before/after the resolution.

Thank you for your kindness

**Comment by surfdude29** [comment]
> […] Yes of course, it's the first time I'm participating so I didn't know if I should tag the issue (https://github.com/bluesky-social/social-app/issues/7699) I'm solving…

As a tip, if you use a keyword you can easily [link a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue) ([en français](https://docs.github.com/fr/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue)). So for example, if you edit the description to say

> Fixes #7699

then if and when this PR is merged, the linked issue will be automatically closed 💫

**Review by haileyok — APPROVED** [review]
Thanks! Gave it a spin, seems to work. Appreciate you fixing that up.
