### PR TITLE
Fix linking to specific search results

### LINKED ISSUE #1384: Bug when I link to a search result within bsky
What is happening here? Chrome and Firefox on Mac

https://bsky.app/profile/manuschwendener.bsky.social/post/3k6nxu63l2o23 

When I just click on the link in the post, I get to https://bsky.app/search = the URL gets cut. 

When I open the link with right click -> 'Open Link in New Tab', I get to https://bsky.app/search**?q=bookshop**, which is the URL I pasted. 

When I open the link in a new tab with cmd&click, I get to https://bsky.app/search  

(Even better would be if the separate tab _Users_ would lead to a separate URL, but that's not urgent).

### PR DESCRIPTION
**Pull request by mozzius**
Fix #1384, #4749

Part of it is stopping `convertBskyAppUrlIfNeeded` from stripping the search param. this is all that's needed for web

However, for native, the search screen is only available in the search tab. so we need to add some custom logic to the link component to support switching to a child route in a different tab, which is used if `screen` is not in `routeNames`.

I opted to only add this to the new link component since that's what we use within posts.

# Test plan

Test web + native. I can't think of any scenario where this code would run other than a link to another tab? so links to `/notifications` or `/chat` should also hit it, but that should be fine.
https://bsky.app/profile/samuel.bsky.team/post/3lruzfzrios2u

### CODE REVIEW

File: src/lib/strings/url-helpers.ts [hunk 1]
```diff
@@ -193,6 +193,11 @@ export function convertBskyAppUrlIfNeeded(url: string): string {
         return startUriToStarterPackUri(urlp.pathname)
       }
 
+      // special-case search links
+      if (urlp.pathname === '/search') {
+        return `/search?q=${urlp.searchParams.get('q')}`
+      }
```
Comment (mozzius) [inline src/lib/strings/url-helpers.ts:199]: technically we could use the router parsing to support arbitrary params but
a) seems like overkill
b) better to be overzealous with stripping search params

**Review by estrattonbailey — APPROVED** [review]

**Comment by estrattonbailey** [comment]
Tested with a link to a chat too
