### PR TITLE
Make posts behave more like links

### LINKED ISSUE #1288: Hovering a post should display a hand cursor
**Describe the bug**
Hovering a post on pc should display a hand cursor to show you can open it. Currently it's only the arrow pointer, or a text cursor if you're over the post's text, making it not obvious you can click on the post.

**To Reproduce**

1. Navigate the skyline and hover a post.

**Expected behavior**

A hand cursor should appear when you hover a post. Similar as on Twitter.

**Details**

- Platform: Firefox 116.0
- Build version: 1.47.0; Platform: web

### PR DESCRIPTION
**Pull request by estrattonbailey**
Closes #1288

Uses CSS to add a `cursor: pointer` to all post cards.

### CODE REVIEW

File: src/view/com/feeds/CustomFeed.tsx [hunk 1]
```diff
@@ -65,7 +65,8 @@ export const CustomFeed = observer(
         testID={`feed-${item.displayName}`}
         accessibilityRole="button"
         style={[styles.container, pal.border, style]}
-        onPress={() => {
+        onPress={e => {
+          e.preventDefault()
```
Comment (estrattonbailey) [inline src/view/com/feeds/CustomFeed.tsx:69]: The `preventDefault` is required for any clickable element within a post that is NOT an `<a>` on web. Otherwise the click/press bubbles up and is handled by the root Post's anchor tag.

File: src/view/com/util/images/AutoSizedImage.tsx [hunk 2]
```diff
@@ -48,10 +55,18 @@ export function AutoSizedImage({
     })
   }, [dim, setDim, setAspectRatio, store, uri])
 
+  const onPressWrapped = React.useCallback(
+    (e: GestureResponderEvent) => {
+      e.preventDefault()
+      if (onPress) onPress()
+    },
+    [onPress],
+  )
```
Comment (estrattonbailey) [inline src/view/com/util/images/AutoSizedImage.tsx:64]: Ensures you can still click straight through to the image lightbox from a feed.

File: src/view/com/util/images/Gallery.tsx [hunk 3]
```diff
@@ -24,10 +30,18 @@ export const GalleryItem: FC<GalleryItemProps> = ({
 }) => {
   const image = images[index]
 
+  const onPressWrapped = React.useCallback(
+    (e: GestureResponderEvent) => {
+      e.preventDefault()
+      if (onPress) onPress(index)
+    },
+    [onPress, index],
+  )
```
Comment (estrattonbailey) [inline src/view/com/util/images/Gallery.tsx:39]: Same as other image, allows lightbox gallery from a feed view

File: src/view/com/util/post-ctrls/PostCtrls.tsx [hunk 4]
```diff
@@ -56,6 +57,14 @@ export function PostCtrls(opts: PostCtrlsOpts) {
...
     [theme],
   ) as StyleProp<ViewStyle>
+
+  const onPressReply = useCallback(
+    (e: GestureResponderEvent) => {
+      e.preventDefault()
+      opts.onPressReply()
+    },
+    [opts],
+  )
```
Comment (estrattonbailey) [inline src/view/com/util/post-ctrls/PostCtrls.tsx:67]: All three post ctrls buttons need this. The context menu button was fine.

**Review by pfrazee — APPROVED** [review]
Looks good!

**Comment by benharri** [comment]
middle click doesn't seem to be working, but the cursor is showing as a pointer
