### PR TITLE
Temporarily use English for Esperanto `intl-displaynames` polyfill

### LINKED ISSUE #9580: Regression: change language page broken
### Steps to Reproduce

If you go to the "change language" page on Android with not-english, the app will break.

### Attachments

Image

### What platform(s) does this occur on?

Android

### Device Info

Samsung Galaxy S25 Ultra

### What version of the app are you using?

1.112.0.774

### Additional Information

Looking at the i18n files, your English i18n was updated 4 days ago, and is 18 lines longer than the others, so there is likely a key that was added, and none of the other i18n files were re-generated.

Future mitigation steps could include checking the i18n file lengths to make sure they match (easy solution) or have the same key and file associations, before releasing to prod.

I guess you could also diff the output of `tail -n+21 <file> | grep -v msgstr`

### PR DESCRIPTION
**Pull request by surfdude29**
> [!IMPORTANT]
> This fix seems logical to me, but I haven't tested it.

In #9473, the `formatjs/intl-displaynames` polyfill was added to provide localization of territory and language display names where `Intl.DisplayNames` isn't supported (especially on native).

This seems to work well for all the app languages we support, with the exception of Esperanto. There seems to be a bug in the [package](https://www.npmjs.com/package/@formatjs/intl-displaynames?activeTab=code), because there isn't actually any data in the `locale-data/eo.js` file:

IMG_9971

So when the app tries to load the polyfill's locale data for Esperanto, it crashes:

IMG_9969

A point to note is that CLDR data is indeed available for both [languages](https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-localenames-full/main/eo/languages.json) and [territories](https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-localenames-full/main/eo/territories.json) in Esperanto.

Until the bug is fixed in `formatjs/intl-displaynames`, this PR proposes simply using English display names instead.

@szafranek13

Fixes #9580

___

## Test Plan

1. On native, open [Settings > Languages](https://bsky.app/settings/language) and change the **App Language** to **Esperanto**
2. Tap the **Content Languages** selector
3. List should open with language names in English

### CODE REVIEW

File: src/locale/i18n.ts [hunk 1]
```diff
@@ -138,7 +138,7 @@ export async function dynamicActivate(locale: AppLanguage) {
       await Promise.all([
         import('@formatjs/intl-pluralrules/locale-data/eo'),
         import('@formatjs/intl-numberformat/locale-data/eo'),
-        import('@formatjs/intl-displaynames/locale-data/eo'),
+        import('@formatjs/intl-displaynames/locale-data/en'),
```
Comment (mozzius) [inline src/locale/i18n.ts]: no need to use the `en` version as it's imported at the top
```suggestion
        // borked, see https://github.com/bluesky-social/social-app/pull/9574
        // import('@formatjs/intl-displaynames/locale-data/eo'),
```

Comment (surfdude29) [reply src/locale/i18n.ts]: Ah of course, thanks
