### PR TITLE
Fix post time localization on Android

### LINKED ISSUE #6728: Post time in Chinese cannot be localized on Android
### Steps to Reproduce

1. Switch the app language to any Chinese language (zh-CN, zh-TW, or zh-HK).
2. Open the details of a post.

Post time displayed in English format, instead of Chinese.

### Attachments

Android:
IMG_2295

iOS:
IMG_2294

### What platform(s) does this occur on?

Android

### Device Info

Pixel 8, Android 15

### What version of the app are you using?

Build version: 1.94.0.402; Bundle info: 3c30bb1 (prod); Bundle date: 24111623; Platform: android; Platform version: 34

### Additional Information

I have no idea, but it seems to only happen on the Android platform. It works fine on iOS and Web.

Tested on the Android emulator as well, and the issue persists.

### PR DESCRIPTION
**Pull request by auroursa**
Fix #6728

It seems that the post date localization on Android is handled differently from Web and iOS. In some cases, this may cause the date localization to not work properly on Android. Here are some examples:

### Before

**Japanese (Web)**
screenshot 2024-11-26 131646

**Chinese (Web)**
screenshot 2024-11-26 131735

**Android**
| Chinese | Japanese |
| ----------- | ----------- |
|  |  |

For Chinese, this date format is like rolling back to English, so it needs to be changed. At the very least, it should match the date format used on the web. The example after the fix:

### After

**Android**
| Chinese | Japanese |
| ----------- | ----------- |
|  |  |

### CODE REVIEW

**Comment by surfdude29** [comment]
This looks like a great solution, nice work 👌 (although I say that as someone who can't code or build the app to test it out, of course 😅)

One quick question: I can't read either Japanese or Chinese, are the correct date formats really exactly the same in the two languages? I must admit I never would have guessed that was the case 🤷🏻‍♂️

**Comment by tkusano** [comment]
the screenshot attached as "After / Japanese (Android)" looks good to me.

**Comment by auroursa** [comment]
It also fixes the localization of timestamps for archived posts.

### Chinese
| Before | After |
| ----------- | ----------- |
|  |  |


### Japanese
| Before | After |
| ----------- | ----------- |
|  |  |

File: src/lib/strings/time.ts [hunk 1]
```diff
@@ -1,12 +1,36 @@
+import {DateTimeFormat} from '@formatjs/intl-datetimeformat'
```
Comment (gaearon) [inline src/lib/strings/time.ts:1]: We'd like to avoid importing something that isn't used on the web. Let's instead fork this file like `time.ts` vs `time.web.ts` and keep this import in the native version. This also lets you remove the inline checks.

**Review by gaearon — CHANGES_REQUESTED** [review]
let's tweak to fork the file instead

File: src/lib/strings/time.ts (hunk 1 above)
Comment (gaearon) [reply src/lib/strings/time.ts:1]: In fact, maybe it's worth moving the code into `time.android.ts` if we're sure the fix is only needed there

**Comment by auroursa** [comment]
Reverted `time.ts`, and made the necessary changes to `PostThreadItem.tsx`

I believe the changes are only needed there for now, other time localizations seem fine.

**Comment by surfdude29** [comment]
I think the entries for `an` and `ast` are missing (merged since you created this PR) 👀

https://github.com/bluesky-social/social-app/blob/b8b15f64d32f751186a50aa7df7826ef83ab2972/src/locale/i18n.ts#L51-L55

https://github.com/bluesky-social/social-app/blob/b8b15f64d32f751186a50aa7df7826ef83ab2972/src/locale/i18n.ts#L59-L63

`ast` is supported by [`@formatjs/intl-numberformat`](https://www.npmjs.com/package/@formatjs/intl-datetimeformat?activeTab=code) but not `an`.

For `an` I suggest `es` is used instead, like we do for `@formatjs/intl-numberformat`.

**Comment by auroursa** [comment]
Spent some time checking the date localization for other languages, including the newly added `an` and `ast`, it should work fine.

Especially, I checked the time localization for English (UK) on Android to ensure it's in DDMMYYYY format. cc @surfdude29

File: src/view/com/post-thread/PostThreadItem.tsx [hunk 2]
```diff
@@ -740,6 +742,7 @@ function ExpandedPostDetails({
   const {_, i18n} = useLingui()
   const openLink = useOpenLink()
   const isRootPost = !('reply' in post.record)
+  const niceDate = isAndroid ? niceDateAndroid : niceDateWebOriOS
```
Comment (gaearon) [inline src/view/com/post-thread/PostThreadItem.tsx:745]: We shouldn't need this. The build system will automatically pick up the `.android` file fork; you should import the main file like before.

Comment (auroursa) [reply src/view/com/post-thread/PostThreadItem.tsx]: Sorry I didn't notice that before, revented `PostThreadItem.tsx`.

File: yarn.lock [hunk 3]
```diff
@@ -4258,6 +4258,31 @@
     "@formatjs/intl-localematcher" "0.5.4"
     tslib "^2.4.0"
 
+"@formatjs/ecma402-abstract@2.2.4":
```
Comment (gaearon) [inline yarn.lock:4261]: We have two copies of this in the lockfile now. I think we need to bump other related libraries in `package.json` so that we have everything in a lockstep and transitive dependencies are shared as much as possible.

File: src/locale/i18n.ts [hunk 4]
```diff
@@ -1,8 +1,10 @@
 // Don't remove -force from these because detection is VERY slow on low-end Android.
 // https://github.com/formatjs/formatjs/issues/4463#issuecomment-2176070577
 import '@formatjs/intl-locale/polyfill-force'
+import '@formatjs/intl-datetimeformat/polyfill-force'
```
Comment (gaearon) [inline src/locale/i18n.ts:4]: Just flagging we need to measure the startup time impact of this on a real android device. We've had pretty bad regressions in the past due to related changes.

Another thing we might want to consider is forking this block between iOS and Android. If this is really android-only, it would be good to avoid activating this on iOS.

Comment (gaearon) [reply src/locale/i18n.ts:4]: Actually maybe you can move this import to `time.android.ts`? Since that's the only place that needs that API. I realize this makes it a bit inconsistent but it does avoid potentially regressing something on iOS.

Comment (gaearon) [reply src/locale/i18n.ts:4]: I guess I'm not sure whether that would break the dynamic imports below. Do they rely on ordering?

**Comment by auroursa** [comment]
I will test it on Android and iOS later and update the `yarn.lock`.

About performance issues, will simulate a low-performance Android device to verify its impact.

Not entirely sure whether to introduce this on iOS as well since the behavior on iOS currently seems consistent with the Web.

Needs conduct more detailed tests over the next few days to carefully ensure nothing breaks.

**Comment by gaearon** [comment]
I wonder what the source of discrepancy is. So far Android/iOS have been consistent with other 18n stuff.

**Comment by auroursa** [comment]
> I wonder what the source of discrepancy is. So far Android/iOS have been consistent with other i18n stuff.

It seems that lingui has an issue when handling long-format dates, as this part is directly formatted through lingui.

Maybe I’ll create a minimal reproducible example to report this to upstream, as the issue consistently appears with both the previously used v4.5.0 and the latest v4.14.1 in RN 0.76. And it only affects certain asian languages on Android.

**Comment by auroursa** [comment]
Just a personal thought, maybe we could try having iOS format the time using DateTimeFormat as well. We could still maintain the i18n-related imports in one place, which might help avoid additional maintenance effort.

After cleaning the lockfile, I retested on both iOS and Android, and the time formatting works correctly on iOS as well. I haven’t done rigorous flame graph testing on performance yet, but there doesn’t seem to be a significant impact on the app’s startup time on a simulated low-end Android device.

**Comment by auroursa** [comment]
I submitted an [issue](https://github.com/lingui/js-lingui/issues/2123#issuecomment-2543394990) with a minimal reproducible example to Lingui, and this is the response I received:

> Lingui does not format dates by itself. It internally uses https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl.
> 
> If dates are not formatted correctly for you it's most likely because you need to set up the polyfill: https://lingui.dev/tutorials/react-native#polyfilling-intl-apis

Based on this I adjusted this PR. We still need to include `intl-datetimeformat`, but no longer need to fork `time.ts`.

**Comment by timofei-iatsenko** [comment]
FYI, you also might be interested in that PR (not merged yet) in the lingui https://github.com/lingui/js-lingui/pull/2117

**Comment by auroursa** [comment]
> FYI, you also might be interested in that PR (not merged yet) in the lingui [lingui/js-lingui#2117](https://github.com/lingui/js-lingui/pull/2117)

Thank you for pointing that out! 5.x also has some features that I'm particularly interested in, such as print placeholder values. I’ll check it again once it’s merged.

For now, I'd like to introduce polyfill to address the current issues, since it looks like migrating from 4.x to 5.x requires some changes beyond the scope of this PR. I admit I’ve been a bit eager to push this PR forward since it has been bothering me for some time.

Thanks again for clarifying my doubts so thoroughly!

**Comment by gaearon** [comment]
Unrelated to this PR but noticed the DM conversation screen doesn't seem to translate dates:

Screenshot 2024-12-16 at 14 25 24

Wanna look into this?

**Comment by auroursa** [comment]
> Wanna look into this?

Glad to look into this, but I’d like to learn more details. It seems to be working on Android when I tested. Does it happen when opening DM conversation after switching the language?

**Comment by auroursa** [comment]
It hasn’t happened to me at this moment, but I have faced it before. Will look into it and see how to fix it when appropriate.

**Comment by surfdude29** [comment]
Fwiw I see the DM issue too on iOS, e.g. here:
IMG_0872
